server:
  port: 8000
spring:
  application:
    name: shell
  profiles:
    active: local

##################################
# #  高德地图参数配置  # #
##################################
gaode:
  key: ${GAODE_KEY:176ff023a2e89881f7caffc831fa3893}
  secret: ${GAODE_SECRET:4b38b4f925c940f5aa33a15e6f860319}